

const numero1 = 30;
const numero3 = 402;

console.log(numero1)

try {
    console.log(numero2)
} catch (error) {
    console.log(error)
    
}

console.log(numero3)

